name: CD
on:
  push:
    tags:
      - '*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set tag output"
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: "Configure git"
        run: |
          git config --global user.name 'Deploy Trigger Automation'
          git config --global user.email 'deploy-trigger-automation@github.com'
      - name: "Push new version to dev"
        run: |
          git branch
          git checkout dev
          echo ${{ steps.vars.outputs.tag }} > VERSION
          git add VERSION
          git commit -m "Update VERSION"
          git push origin dev
      - name: "Trigger deployment"
        run: |
          git checkout master
          git pull origin dev
          git push origin master
