name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    name: "Tests ${{ matrix.python-version }} on ${{ matrix.platform }}"
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
          - windows-2019
          - windows-2022
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        exclude:
          - platform: ubuntu-22.04
            python-version: 3.6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Run tests with Python ${{ matrix.python-version }} on ${{ matrix.platform }}"
        run: |
          python -m unittest discover tests/
  coverage:
    name: "Coverage Report"
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
      - name: "Run tests with coverage report"
        run: |
          coverage run -m unittest discover tests/
          coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: pynotifier_lib
          name: pynotifier_lib
          fail_ci_if_error: true
          verbose: true
