name: CI
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    name: "Tests ${{ matrix.python-version }} on ${{ matrix.platform }}"
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Run tests with Python ${{ matrix.python-version }} on ${{ matrix.platform }}"
        run: |
          python tests/main.py
  coverage:
    name: "Coverage Report"
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.6"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
      - name: "Run tests with coverage report"
        run: |
          coverage run tests/main.py
          coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: backend
          name: backend
          fail_ci_if_error: true
          verbose: true
