name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: "Deploy to PyPi"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: "Deploy using twine"
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m pip install --upgrade setuptools wheel
          python3 setup.py sdist bdist_wheel
          python3 -m pip install --upgrade twine
          twine upload --non-interactive --verbose dist/*
